name: Runs checks on the project
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Run linter
        run: echo "Running linter..."

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Run tests
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Build project
        run: npm run build
      